personal_portfolio/blog/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings # gets settings from settings.py file
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/personal_portfolio/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings # gets settings from settings.py file
from django.urls import include, path
from portfolio import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_portfolio/blog/models.py
from django.db import models


class Blog(models.Model):

    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    date = models.DateField(auto_created=True)
    text = models.TextField()

    def __str__(self):
        return self.title

personal_portfolio/portfolio/models.py
from django.db import models


class Project(models.Model):

    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True) # blank makes it optional

    def __str__(self):
        return self.title

personal_portfolio/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def all_blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html',
                  {'blogs': blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html',
                  {'blog': blog})

personal_portfolio/portfolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html',
                  {'projects': projects})

personal_portfolio/blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h1>All Blogs</h1>

<h2>There are {{ blogs.count }} blog{{ blogs.count|pluralize }}</h2>

{% for blog in blogs %}
  <a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
  <h3>{{ blog.date|date:'M d Y'|upper }}</h3>
  {{ blog.description }}<br>
  {{ blog.text|safe|truncatechars:100 }}
{% endfor %}


{% endblock %}

personal_portfolio/blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}
<h1>{{ blog.title }}</h1>

<h2>--{{ blog.date|date:'F jS Y' }}--</h2>

<p>{{ blog.text|safe }}</p>

{% endblock %}

personal_portfolio/portfolio/templates/portfolio/base.html
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <title>Rachel's Portfolio</title>
</head>

<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% block content %}{% endblock %}

</body>

personal_portfolio/portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}
  <h1>Rachel's Portfolio</h1>

  {% load static %}


  <a href="{% url 'blog:all_blogs' %}">Blog</a>
  <br>

  <a href="{% static 'portfolio/static_analysis_notes.pdf' %}">Resume</a>
  <br>
  <img src="{% static 'portfolio/sleeping_ed.jpg' %}" width="400px;">

  <h3>New change!</h3>

  {% for project in projects %}
    <h2>{{ project.title }}</h2>
    <p>{{ project.description }}</p>
    <img src="{{ project.image.url }}" width=200px;>
    {% if project.url %}
      <br>
      <a href="{{ project.url }}">Link</a>
    {% endif %}
  {% endfor %}

{% endblock %}